### PR TITLE
Update target bash scripts for compatibility with MacOS bash

### PR DESCRIPTION
**Pull request by cmdshepard**
# MacOS Compatibility

@anishkny identified a a compatibility issue in the scripts that impacted the MacOS terminal. The update was also tested for compatibility on Linux bash (Ubuntu 16.04).

---

**This contribution is a courtesy of [Kater Technologies](https://kater.com)**

---

### CODE REVIEW

**Comment by leonchen83** [comment]
merged.
this weekend(UTC+08:00) will release redis-rdb-cli-v0.1.17

**Comment by cmdshepard** [comment]
thanks @leonchen83

**Comment by leonchen83** [comment]
@cmdshepard 
this bash scrpits could not handle soft link in linux system
for example
`ln -s /path/to/redis-rdb-cli/bin/rct /usr/bin/rct`
and then run `rct` we could not get the real path of rct

**Comment by cmdshepard** [comment]
@anishkny please see above

**Comment by cmdshepard** [comment]
@anishkny @leonchen83 
this could be a potential solution, what do you guys think?
https://stackoverflow.com/questions/3466166/how-to-check-if-running-in-cygwin-mac-or-linux

**Comment by leonchen83** [comment]
@anishkny @cmdshepard 
LGTM

```sh
argv0=$(echo "$0" | sed -e 's,\\,/,g')
basedir=$(dirname "$(readlink "$0" || echo "$argv0")")

case "$(uname -s)" in
  Darwin) basedir="$( cd "$( dirname "$argv0" )" && pwd )";;
  Linux) basedir=$(dirname "$(readlink -f "$0" || echo "$argv0")");;
  *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
  *MSYS*) basedir=`cygpath -w "$basedir"`;;
esac
```

**Comment by leonchen83** [comment]
I have committed related code to dev branch

**Comment by cmdshepard** [comment]
@leonchen83 looks good! thank you

**Pull request merged**
